# Config file for your experiments, this will overwrite/merge your default.py config file

DATASET:
  NAME: "KittiDataset" 
  PATH: "./datasets/kitti_object/training"
  LENGTH: 7500

ARCHITECTURE:
  MODEL: "FasterRCNN"
  
LOGS:
  BASE_PATH: "./logs"

SEED: 5
USE_CUDA: True

TRAIN:
  BATCH_SIZE: 32
  EPOCHS: 65
  LR: 1e-3
  LR_DECAY: 0.5
  MOMENTUM: 0.9
  MILESTONES: (20,35,55)
  DSET_SHUFFLE: True
  SAVE_MODEL_EPOCHS: 5
  DATASET_DIVIDE: 0.9

INPUT:
  IMAGE_SIZE: (375,1242)
  LABELS_TO_TRAIN: ['Car', 'Van', 'Truck', 'Tram', 'Pedestrian', 'Person_sitting', 'Cyclist']
  NUM_CLASSES: 7

ANCHORS:
  ANCHOR_SCALES: [32, 64, 128, 256]

ROI_HEADS:
  LOSS_TYPE: "loss_attenuation"
  SCORE_THRESH_TEST: 0.25

SOLVER:
  OPTIM: "sgd"
