# Config file for your experiments, this will overwrite/merge your default.py config file

DATASET:
  NAME: "KittiDataset" #option: "detections", "tracking"
  PATH: "/network/home/bansaldi/Denso-OD/datasets/kitti_dataset/training"
  LENGTH: 7000
  # TRACKS: 

ARCHITECTURE:
  MODEL: "FasterRCNN"

LOGS:
  BASE_PATH: "/network/home/bansaldi/Denso-OD/logs"

SEED: 5
USE_CUDA: True

TRAIN:
  BATCH_SIZE: 6
  EPOCHS: 50
  LR: 1e-3
  LR_DECAY: 0.5
  MOMENTUM: 0.9
  MILESTONES: (10,20)
  DSET_SHUFFLE: False
  SAVE_MODEL_EPOCHS: 5
  DATASET_DIVIDE: 0.9

INPUT:
  IMAGE_SIZE: (375,1242)
  LABELS_TO_TRAIN: ['Car', 'Van', 'Truck', 'Tram', 'Pedestrian', 'Person_sitting', 'Cyclist']
  NUM_CLASSES: 7

ROI_HEADS:
  LOSS_TYPE: "deterministic"
